---
apiVersion: v1
kind: Namespace
metadata:
  name: tooling

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: tooling

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-releases-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: tooling
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""