---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certManager.cloudflareSecretName }}
  # HAS TO BE IN THE SAME NAMESPACE AS CERT-MANAGER ITSELF!
  namespace: cert-manager
data:
   api-key: {{ .Values.certManager.cloudflareApiKey | b64enc }}
